nginx:
  imagePullSecrets:
    - name: "private-registry"

  # TODO: renovate setup
  image: ###ZARF_REGISTRY###/ironbank/opensource/nginx/nginx-alpine:1.25.3

machineid:
  imagePullSecrets:
    - name: "private-registry"

  image: 
    pause:
      # TODO: renovate setup
      image: ###ZARF_REGISTRY###/ironbank/opensource/pause/pause:3.9
    
    wolfi:
      # TODO: renovate setup
      image: ###ZARF_REGISTRY###/chainguard/wolfi-base:latest