# See the UDS RKE2 repository's documentation, `docs/ROOK-CEPH.md` for more details on values overrides

imagePullSecrets:
  - name: private-registry

toolbox:
  enabled: true
  # TODO: setup renovate
  image: ###ZARF_REGISTRY###/ironbank/opensource/ceph/ceph:v18.2.2

cephClusterSpec:
  mon:
    count: 1
    allowMultiplePerNode: true

  mgr:
    count: 1
    allowMultiplePerNode: true
    modules:
      - name: "rook"
        enabled: true

  cephConfig:
    global:
      osd_pool_default_size: "1"
      osd_pool_default_min_size: "1"
      osd_pool_default_pg_num: "1"
      mon_warn_on_pool_no_redundancy: "false"
      bdev_flock_retry: "20"
      bluefs_buffered_io: "false"
      mon_data_avail_warn: "10"

  cephVersion:
    # TODO: setup renovate
    image: ###ZARF_REGISTRY###/ironbank/opensource/ceph/ceph:v18.2.2
    allowUnsupported: true

  dashboard:
    enabled: true
    ssl: false

  monitoring:
    enabled: ###ZARF_VAR_ENABLE_MONITORING###
    rulesNamespace: "rook-ceph"
    createPrometheusRules: false

  disruptionManagement:
    managePodBudgets: false
    osdMaintenanceTimeout: 30
    manageMachineDisruptionBudgets: false

  network:
    # Use host networking to avoid CNI causing storage issues
    # Equivalent to legacy `hostNetwork: true`
    provider: "host"
    connections:
      encryption:
        enabled: true

  storage:
    useAllNodes: true
    useAllDevices: true
    devices:
      - name: ###ZARF_VAR_DEVICE_NAME###
    config:
      osdsPerDevice: "1"
      deviceClass: ###ZARF_VAR_DEVICE_CLASS###

cephBlockPool:
  enabled: ###ZARF_VAR_ENABLE_CEPH_BLOCK_STORE###
  spec:
    failureDomain: "host"
    isDefault: ###ZARF_VAR_CEPH_BLOCK_STORE_AS_DEFAULT###
    replicated:
      size: 1

cephFileSystem:
  enabled: ###ZARF_VAR_ENABLE_CEPH_FILE_STORE###
  spec:
    dataPools:
      - failureDomain: "host"
        replicated:
          size: 1
        compressionMode: "none"
    metadataPool:
      replicated:
        size: 1
    metadataServer:
      activeCount: 1
      activeStandby: false
  storageClass:
    isDefault: ###ZARF_VAR_CEPH_FILE_STORE_AS_DEFAULT###

cephObjectStore:
  enabled: ###ZARF_VAR_ENABLE_CEPH_BLOCK_STORE###
  spec:
    dataPools:
      replicated:
        size: 1
    metadataPool:
      replicated:
        size: 1
      failureDomain: "host"
    dataPool:
      failureDomain: "host"
    gateway:
      instances: 1
  storageClass:
    isDefault: ###ZARF_VAR_CEPH_OBJECT_STORE_AS_DEFAULT###
    parameters:
      region: ###ZARF_VAR_REGION###
