# TODO: renovate setup
# yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/uds-cli/v0.10.4/tasks.schema.json

variables:
  - name: VERSION
    description: "Explicitly set the version, overriding the official release tag"
    # x-release-please-start-version
    default: "0.4.2"
    # x-release-please-end

  - name: PUBLISH_OPTIONS
    description: "Extra Zarf package publishing options"
    default: "--no-progress --no-log-file --log-level debug -a amd64"
  - name: PUBLISH_BUNDLE_OPTIONS
    description: "Extra UDS bundle publishing options"
    default: "--no-progress --no-tea --no-log-file --log-level debug -a amd64 --confirm"
  - name: TARGET_REGISTRY
    description: "Target registry to publish to"
    default: "ghcr.io"

tasks:
  ##########################
  # ALL PACKAGES AND BUNDLES
  ##########################

  # TODO: re-enable rook-ceph and longhorn when built
  - name: all
    description: "Publishes all Zarf packages in the repository"
    actions:
      # Zarf packages
      - task: uds-rke2
      - task: uds-rke2-infrastructure
      - task: uds-rke2-exemptions-local-path
      - task: local-path
      - task: local-path-init
      - task: minio
      - task: leapfrogai-workarounds
      - task: nvidia-gpu-operator

      # UDS bundles
      - task: local-path-core-bundle

  ###########
  # REUSEABLE
  ###########

  - name: publish
    description: "Publish a Zarf package for the amd64 architectures"
    inputs:
      path:
        description: "Path to the Zarf package being published"
        required: true
      name:
        description: "Name of the Zarf package being published"
        required: true
      targetRepo:
        description: "Repository to publish Zarf package into"
        required: true
    actions:
      - description: "Publish the Zarf package for the amd64 architectures"
        cmd: |
          sudo uds zarf package publish \
            "${{ .inputs.path }}/zarf-package-${{ .inputs.name }}-amd64-${VERSION}.tar.zst" \
            "oci://${TARGET_REGISTRY}/${{ .inputs.targetRepo }}" \
            ${PUBLISH_OPTIONS}

  - name: init
    description: "Publish a Zarf Init package for the amd64 architectures"
    inputs:
      path:
        description: "Path to the Zarf Init package being published"
        required: true
      targetRepo:
        description: "Repository to publish Zarf Init package into"
        required: true
    actions:
      - description: "Publish the Zarf init package for the amd64 architectures"
        cmd: |
          sudo uds zarf package publish \
            "${{ .inputs.path }}/zarf-init-amd64-$(uds zarf version).tar.zst" \
            "oci://${TARGET_REGISTRY}/${{ .inputs.targetRepo }}" \
            ${PUBLISH_OPTIONS}

  - name: bundle
    description: "Publish a UDS bundle for the amd64 architectures"
    inputs:
      path:
        description: "Path to the UDS bundle being published"
        required: true
      name:
        description: "Name of the UDS bundle being published"
        required: true
      targetRepo:
        description: "Repository to publish UDS bundle into"
        required: true
    actions:
      - description: "Publish the UDS bundle for the amd64 architectures"
        cmd: |
          sudo uds publish \
            "${{ .inputs.path }}/uds-bundle-${{ .inputs.name }}-amd64-${VERSION}.tar.zst" \
            "oci://${TARGET_REGISTRY}/${{ .inputs.targetRepo }}" \
            ${PUBLISH_OPTIONS}

  #########
  # UTILITY
  #########

  - name: remote-dev
    description: "Publish a `dev` tag to the remote repository"
    actions:
      - description: "Re-create the `dev` Git tag to trigger the `tag-and-release` workflow"
        cmd: |
          git tag --delete dev
          git push --delete origin dev
          git tag dev && git push origin dev

  #########
  # BUNDLES
  #########

  - name: local-path-core-bundle
    description: "Publish the Local Path Provisioner UDS RKE2 bootstrapping bundle"
    actions:
      - task: bundle
        with:
          path: build/bundles
          name: uds-rke2-local-path-core
          # the OCI reference for UDS bundle publish does not gracefully handle an ending `/`
          targetRepo: justinthelaw/packages/uds/bundles

  ###################
  # STANDARD PACKAGES
  ###################

  - name: uds-rke2
    description: "Publish the UDS RKE2 Zarf package"
    actions:
      - task: publish
        with:
          path: build/packages
          name: uds-rke2
          targetRepo: justinthelaw/packages/uds/

  - name: uds-rke2-infrastructure
    description: "Publish the UDS RKE2 Infrastructure Zarf package"
    actions:
      - task: publish
        with:
          path: build/packages
          name: infrastructure
          targetRepo: justinthelaw/packages/uds/uds-rke2/

  - name: uds-rke2-exemptions-local-path
    description: "Publish the UDS RKE2 service Pepr policy exemptions package"
    actions:
      - task: publish
        with:
          path: build/packages/local-path
          name: exemptions
          targetRepo: justinthelaw/packages/uds/uds-rke2/

  - name: local-path
    description: "Publish the Local Path Provisioner package"
    actions:
      - task: publish
        with:
          path: build/packages/local-path
          name: local-path
          targetRepo: justinthelaw/packages/uds/uds-rke2/

  - name: minio
    description: "Publish the MinIO package"
    actions:
      - task: publish
        with:
          path: build/packages
          name: minio
          targetRepo: justinthelaw/packages/uds/uds-rke2/

  ###############
  # INIT PACKAGES
  ###############

  - name: local-path-init
    description: "Publish the custom Zarf Init package"
    actions:
      - task: init
        with:
          path: build/packages/local-path
          targetRepo: justinthelaw/packages/uds/uds-rke2/

  ########################
  # APP-SPECIFIC PACKAGES
  ########################

  - name: leapfrogai-workarounds
    description: "Publish the LeapfrogAI-specific workarounds package"
    actions:
      - task: publish
        with:
          path: build/packages
          name: leapfrogai-workarounds
          targetRepo: justinthelaw/packages/uds/uds-rke2/

  - name: nvidia-gpu-operator
    description: "Publish the NVIDIA GPU Operator package"
    actions:
      - task: publish
        with:
          path: build/packages
          name: nvidia-gpu-operator
          targetRepo: justinthelaw/packages/uds/uds-rke2/
