# TODO: renovate setup
# yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/uds-cli/v0.10.4/tasks.schema.json

tasks:
  - name: publish
    description: "Publish a Zarf package for the amd64 architectures"
    inputs:
      path:
        description: "Path to the Zarf package being published"
        required: true
      name:
        description: "Name of the Zarf package being published"
        required: true
      targetRepo:
        description: "Repository to publish Zarf package into"
        required: true
    actions:
      - description: "Publish the Zarf package for the amd64 architectures"
        cmd: |
          sudo uds zarf package publish ${{ .inputs.path }}/zarf-package-${{ .inputs.name }}-*.tar.zst oci://${{ .inputs.targetRepo }}

  - name: uds-rke2
    description: "Publish the UDS RKE2 Zarf package"
    actions:
      - task: publish
        with:
          path: build/packages
          name: uds-rke2
          targetRepo: ghcr.io/justinthelaw/packages/uds

  - name: local-path-init
    description: "Publish the custom Zarf Init package"
    actions:
      - task: publish
        with:
          path: build/packages/local-path
          name: init
          targetRepo: ghcr.io/justinthelaw/packages/uds/local-path

  - name: longhorn-init
    description: "Publish the custom Zarf Init package"
    actions:
      - task: publish
        with:
          path: build/packages/longhorn
          name: init
          targetRepo: ghcr.io/justinthelaw/packages/uds/longhorn

  - name: rook-ceph-init
    description: "Publish the custom Zarf Init package"
    actions:
      - task: publish
        with:
          path: build/packages/rook-ceph
          name: init
          targetRepo: ghcr.io/justinthelaw/packages/uds/rook-ceph

  - name: minio
    description: "Publish the MinIO package"
    actions:
      - task: publish
        with:
          path: build/packages
          name: minio
          targetRepo: ghcr.io/justinthelaw/packages/uds

  - name: uds-rke2-exemptions
    description: "Publish the UDS RKE2 service Pepr policy exemptions package"
    actions:
      - task: publish
        with:
          path: build/packages
          name: uds-rke2-exemptions
          targetRepo: ghcr.io/justinthelaw/packages/uds
