# TODO: renovate setup
# yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/uds-cli/v0.10.4/tasks.schema.json

includes:
  - create: ./create.yaml

variables:
  - name: VERSION
    description: "Explicitly set the version, overriding the official release tag"
    # x-release-please-start-version
    default: "0.2.0"
    # x-release-please-end
  - name: OPTIONS
    description: "Extra Zarf package or UDS bundle publishing options"
    default: "--no-progress --no-log-file --log-level warn -a amd64"

tasks:
  - name: all
    description: "Builds and publishes all Zarf packages in the repository"
    actions:
      - task: create:uds-rke2
      - task: uds-rke2
      - task: clean
      - task: create:uds-rke2-infrastructure
      - task: uds-rke2-infrastructure
      - task: clean
      - task: create:uds-rke2-exemptions-local-path
      - task: uds-rke2-exemptions-local-path
      - task: clean
      - task: create:uds-rke2-exemptions-longhorn
      - task: uds-rke2-exemptions-longhorn
      - task: clean
      - task: create:uds-rke2-exemptions-rook-ceph
      - task: uds-rke2-exemptions-rook-ceph
      - task: clean
      - task: create:local-path
      - task: local-path
      - task: clean
      - task: create:local-path-init
      - task: local-path-init
      - task: clean
      # TODO: add these back in when actually built
      # - task: create:longhorn
      # - task: longhorn
      # - task: clean
      # - task: create:longhorn-init
      # - task: longhorn-init
      # - task: clean
      - task: create:rook-ceph
      - task: rook-ceph
      - task: clean
      - task: create:rook-ceph-init
      - task: rook-ceph-init
      - task: clean
      - task: create:minio
      - task: minio
      - task: clean

  - name: publish
    description: "Publish a Zarf package for the amd64 architectures"
    inputs:
      path:
        description: "Path to the Zarf package being published"
        required: true
      name:
        description: "Name of the Zarf package being published"
        required: true
      targetRepo:
        description: "Repository to publish Zarf package into"
        required: true
    actions:
      - description: "Publish the Zarf package for the amd64 architectures"
        cmd: |
          sudo uds zarf package publish \
            "${{ .inputs.path }}/zarf-package-${{ .inputs.name }}-amd64-${VERSION}.tar.zst" \
            "oci://${{ .inputs.targetRepo }}" \
            ${OPTIONS}

  - name: clean
    description: "Cleans the host system of build artifacts"
    actions:
      - description: "Remove the build folder, Docker artifacts, and clear UDS and Zarf caches"
        cmd: |
          sudo uds zarf tools clear-cache && sudo rm -rf ~/.uds-cache && sudo rm -rf ~/.zarf-cache
          sudo docker system prune -a -f && sudo docker volume prune -f
          sudo rm -rf build/ zarf-sbom/ /tmp/zarf-*

  - name: init
    description: "Publish a Zarf Init package for the amd64 architectures"
    inputs:
      path:
        description: "Path to the Zarf Init package being published"
        required: true
      targetRepo:
        description: "Repository to publish Zarf Init package into"
        required: true
    actions:
      - description: "Publish the Zarf init package for the amd64 architectures"
        cmd: |
          sudo uds zarf package publish \
            "${{ .inputs.path }}/zarf-init-amd64-$(uds zarf version).tar.zst" \
            "oci://${{ .inputs.targetRepo }}" \
            ${OPTIONS}

  - name: uds-rke2
    description: "Publish the UDS RKE2 Zarf package"
    actions:
      - task: publish
        with:
          path: build/packages
          name: uds-rke2
          targetRepo: ghcr.io/justinthelaw/packages/uds

  - name: uds-rke2-infrastructure
    description: "Publish the UDS RKE2 Infrastructure Zarf package"
    actions:
      - task: publish
        with:
          path: build/packages
          name: uds-rke2-infrastructure
          targetRepo: ghcr.io/justinthelaw/packages/uds/uds-rke2

  - name: uds-rke2-exemptions-local-path
    description: "Publish the UDS RKE2 service Pepr policy exemptions package"
    actions:
      - task: publish
        with:
          path: build/packages/local-path
          name: uds-rke2-exemptions
          targetRepo: ghcr.io/justinthelaw/packages/uds/uds-rke2

  - name: uds-rke2-exemptions-longhorn
    description: "Publish the UDS RKE2 service Pepr policy exemptions package"
    actions:
      - task: publish
        with:
          path: build/packages/longhorn
          name: uds-rke2-exemptions
          targetRepo: ghcr.io/justinthelaw/packages/uds/uds-rke2

  - name: uds-rke2-exemptions-rook-ceph
    description: "Publish the UDS RKE2 service Pepr policy exemptions package"
    actions:
      - task: publish
        with:
          path: build/packages/rook-ceph
          name: uds-rke2-exemptions
          targetRepo: ghcr.io/justinthelaw/packages/uds/uds-rke2

  - name: local-path
    description: "Publish the Local Path Provisioner package"
    actions:
      - task: publish
        with:
          path: build/packages/local-path
          name: local-path
          targetRepo: ghcr.io/justinthelaw/packages/uds

  - name: local-path-init
    description: "Publish the custom Zarf Init package"
    actions:
      - task: init
        with:
          path: build/packages/local-path
          targetRepo: ghcr.io/justinthelaw/packages/uds/

  - name: longhorn
    description: "Publish the Longhorn package"
    actions:
      - task: publish
        with:
          path: build/packages/longhorn
          name: longhorn
          targetRepo: ghcr.io/justinthelaw/packages/uds

  - name: longhorn-init
    description: "Publish the custom Zarf Init package"
    actions:
      - task: init
        with:
          path: build/packages/longhorn
          targetRepo: ghcr.io/justinthelaw/packages/uds/

  - name: rook-ceph
    description: "Publish the Rook-Ceph package"
    actions:
      - task: publish
        with:
          path: build/packages/rook-ceph
          name: rook-ceph
          targetRepo: ghcr.io/justinthelaw/packages/uds

  - name: rook-ceph-init
    description: "Publish the custom Zarf Init package"
    actions:
      - task: init
        with:
          path: build/packages/rook-ceph
          targetRepo: ghcr.io/justinthelaw/packages/uds

  - name: minio
    description: "Publish the MinIO package"
    actions:
      - task: publish
        with:
          path: build/packages
          name: minio
          targetRepo: ghcr.io/justinthelaw/packages/uds
