# TODO: renovate setup
# yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/uds-cli/v0.10.4/tasks.schema.json

variables:
  - name: DISK_NAME
    description: "The name of a Ceph-formatted disk (e.g. /dev/ubuntu-vg/ceph) that is to be wiped."
    default: "dm-1"

tasks:
  #########
  # UTILITY
  #########

  - name: semi-clean
    description: "Cleans the host of extraneous build artifacts"
    actions:
      - description: "Remove the build folder and clear UDS and Zarf caches"
        cmd: |
          sudo uds zarf tools clear-cache && sudo rm -rf ~/.uds-cache && sudo rm -rf ~/.zarf-cache
          sudo rm -rf build/ zarf-sbom/ /tmp/zarf-*

  - name: full-clean
    description: "Cleans the host system of extraneous build artifacts, to include hanging Docker artifacts"
    actions:
      - task: semi-clean
      - description: "Remove the build folder, Docker artifacts, and clear UDS and Zarf caches"
        cmd: sudo docker system prune -a -f && sudo docker volume prune -f

  - name: local-registry
    description: "Create a local image registry for development"
    actions:
      - description: "Create a local Docker registry"
        cmd: docker run -d -p 5000:5000 --restart=always --name registry registry:2

  - name: rook-ceph-destroy
    description: "Destroys an existing Rook-Ceph cluster installation and all associated data on the host node"
    actions:
      - description: "Run the Rook-Ceph destroy script"
        cmd: |
          DISK_NAME=${DISK_NAME} /root/uds-rke2-artifacts/rook-ceph/rook-ceph-destroy.sh

  - name: uds-rke2-destroy
    description: "Destroys an existing RKE2 cluster installation and all associated artifacts"
    actions:
      - description: "Run the RKE2 destroy script"
        cmd: |
          /root/uds-rke2-artifacts/rke2-destroy.sh
          sudo rm -rf /root/uds-rke2-artifacts/
          sudo rm -rf /opt/uds/pvc-*
