# TODO: renovate setup
# yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/uds-cli/v0.10.4/tasks.schema.json

includes:
  - create: ./create.yaml
  - deploy: ./deploy.yaml
  - setup: ./setup.yaml

variables:
  - name: VERSION
    description: "Explicitly set the version, overriding the official release tag"
    # x-release-please-start-version
    default: "0.4.2"
    # x-release-please-end

tasks:
  - name: uds-rke2
    description: "Deploy a new RKE2 cluster"
    actions:
      - task: setup:clean

      - task: create:uds-rke2
      - task: deploy:uds-rke2-bootstrap
        with:
          joinToken: "my-test-token"

  - name: local-path-minio-init
    description: "Deploy the Local Path Provisioner + MinIO Zarf Init"
    actions:
      - task: setup:clean

      - task: create:local-path-init
      - task: deploy:local-path-init
        with:
          # overcome GitHub runner free space constrains
          extraOptions: "--set BUCKET_PERSISTENCE_SIZE=1Gi --set REGISTRY_PVC_SIZE=10Gi"

      - task: setup:clean

      - task: create:uds-rke2-infrastructure
      - task: deploy:uds-rke2-infrastructure

  - name: leapfrogai-specific-packages
    description: "Deploy the LeapfrogAI workarounds and NVIDIA GPU operator"
    actions:
      - task: setup:clean

      # Unexplained workaround for GH runner issues during CoreDNS pod validation
      # TODO: see issue for more details
      - cmd: sudo uds zarf tools kubectl describe nodes

      - task: create:leapfrogai-workarounds
      - task: deploy:leapfrogai-workarounds

      - task: setup:clean

      - task: create:nvidia-gpu-operator
      - task: deploy:nvidia-gpu-operator
