package:
  create:
    set:
      # x-release-please-start-version
      version: "0.6.1"
      # x-release-please-end

      storage_configuration_values_file: values/storage-configuration-values.yaml
