apiVersion: v1
kind: Service
metadata:
  name: zarf-connect-longhorn-ui
  labels:
    # Enables "zarf connect longhorn-ui"
    zarf.dev/connect-name: longhorn-ui
  annotations:
    zarf.dev/connect-description: "Connect to the Longhorn User Interface"
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: longhorn-ui
