options:
  log_level: debug
  architecture: amd64

shared:
  domain: uds.local

variables:
  uds-rke2:
    join_token: $JOIN_TOKEN

  infrastructure:
    network_interface: $NETWORK_INTERFACE

  local-path-init:
    # Workaround for SELinux EBS issue - https://github.com/bottlerocket-os/bottlerocket/issues/2417
    registry_hpa_enable: false
    registry_pvc_size: 100Gi
    # Set this to ReadWriteMany for multi-node, HA situations
    # See documentation on the StorageClass Zarf Init flavors for more details
    registry_pvc_access_mode: ReadWriteOnce
    storage_configuration_values_file: values/storage-configuration-values.yaml

    # MinIO bucket persistence volume size
    bucket_persistence_size: 50Gi

  uds-core:
    loki_s3_endpoint: http://minio.minio.svc.cluster.local:9000
    loki_chunks_bucket: uds
    loki_ruler_bucket: uds
    loki_admin_bucket: uds
    loki_s3_region: us-east-1
    loki_s3_access_key_id: uds
    loki_s3_secret_access_key: uds-secret
    loki_irsa_role_arn: ""
    loki_write_replicas: 1
    loki_read_replicas: 1
    loki_backend_replicas: 1

    velero_use_secret: false
    velero_irsa_role_arn: ""

    # Zarf variables not available via UDS bundle values path overrides
    velero_bucket: uds
    velero_bucket_region: us-east-1
    velero_bucket_provider_url: http://minio.minio.svc.cluster.local:9000
    velero_bucket_credential_name: uds
    velero_bucket_credential_key: uds-secret

    # TLS CERT and KEY values must be base64 encoded
    # Paste the entire TLS CERT or KEY value into the fields below
    # TODO: auto-replace the field upon `create:tls`
    admin_tls_cert: >
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVzekNDQXBzQ0ZBdFJ5MkQwZU9RUEJFSTcw
      ZExFSnBBOU52QlZNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1CWXgKRkRBU0JnTlZCQU1NQ3lvdWRXUnpM
      bXh2WTJGc01CNFhEVEkwTURjeE1ERTVNekExTUZvWERUSTFNRGN4TURFNQpNekExTUZvd0ZqRVVN
      QklHQTFVRUF3d0xLaTUxWkhNdWJHOWpZV3d3Z2dJaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUNE
      d0F3Z2dJS0FvSUNBUURmd2htK2s5bWx4KzNqSVZsYlhqRlR0V2VjZW9OUmRPNWNZK2pyeURJMU5t
      VzgKWjBZbzh3MG4rcTZwblNOd0JoWlNFWVNTL3JxeitjRXB1NVloTmFWVnVuUmZ5Qjk4dkRXbHND
      ZkkyZjhZejExMQpYYlJGQWZBMjFJeXpEZE5EMVgrY0orV2RYRXNBUG5JNjJEQ21BVk1VMTZUMWdW
      K1EzNUduZlRFZmR6RjMrTklxCmtwVmF6am5DV0N5R0dLRVVPcmw3TVdCeERTOWc0N2dHTmhGN0ZM
      Rk5ycEEvYnI3eUdmMU03UEhNMFVRSFRtTjAKdzVuZDdlcVNHMHFhM1lvTkxuU1NsS2dWNGM1Tlpt
      ZS9UMWhqOE1sdTZESkd6ejlTY24yTE04azZxN1gyRCttSgpjbDJ1V0U5ZEMvcHlUbG54aERpVG04
      T0lWWnhKYWhla1U5VHVwb3lKdkFvZm1XMWxNejJMdWdwZGt3R3BEc3BiCnhsM28xTFN0ZCtPYTY1
      b2NldUQ4cWlLaktoWE96ZnRYQzZFUnNSam1QVXF4dWE4OW9iSHdBMWh0ZlhyTUtHVk8KNkVLK1Aw
      WkNBanZRYkdSWFFWblNSSFFBQnBQM1d2Q2l2Q0ZybWdCOGZSR0RuaVZqRWtDYWNOTGxLcjVaV1pr
      SwptZXl3ajNWU1FNSWRBK0pSeHBRUFdPTllvcnpneCsyV1BKa3A1Zmp1NjhDSG5tMFlXcEVSOTM2
      TU55ZkYzVWtmCk80WFpaUlJVQUhkUlVTNDQ0b3pTd012djZMOVJWY1gxSmtHWFJ4UWJNNC81RzVJ
      T0xucWFGR1pvSnFHaFRMUWQKaW8yOXRjRm1CK1crbXlWd01WQkZsdVk3NWRldEhUZjF1ZnZheEl0
      OUFVUUtuMi9POHJ0VHMxTGgwRVlLcFFJRApBUUFCTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElDQVFC
      ZVp2cDM0NElqWlN4eWR3S0c1L3UxT0tqU0ZLSnA5eHhTCm1OWjBNQnpDNjdUZWJTMzR6NlRKZWZU
      UmxWVndOYXR2LzhVSkhGYlVnL2xQTi9vTGpXSFJtRkNwUE1yNWJoYnYKV2dneGRHM2thZ29HRHVM
      MlZhYjhPRTJNRTJwSDJkZDBLL0VxbEo3OEJQNHBDOFpTL3Yxc1Y4QlRDYVQrNWlUMgpFVjR4Q2VD
      cnk3N3Yrczl1TUZPRzBHbHlmVkluQU4xSlk4cXQyMVFJR3pyTCtrQndoaHFVaS8wY1hDTUxjUWgw
      ClRHYk5PY0RZV2kxdHhjSHE0SzZ0YkI4M2crM2JjZ25SeitubkltMEpXR1h6OTVsTGNFdjZpUzVq
      ZVNBb2oyaXQKK0E4dHAyWnFId1lic0JUVDBEbmJ5b1hJVFg1dllOYkZoWHM5cm1qNWFTUGdaM1Qx
      WGFPdittMXJYbm92MXBzaAo5YytEQWpDRHVnZDJ4OUlpZzFOSVVCQndwUDVGS1QyMFlEWG41Rlp5
      N2JkdzBzdldyL2x3azBSeVNFQzdIRTBjClNKNnJCU0RBbVB1VHRmaElPVERMVWY4STZib2VUeCs5
      Mmk3OCt2aklXZ1gzUEZtY1ZZOVY3RUVycGR0dmtnc2YKL2s3NDRhWVd0L0IxNy9NeFlIV2RUS0ZW
      c2U1bXB3SWErK1djbTVnS3VSVTRRUWM3MTBjNE94bDF2OE15T0Z3ZgpvYlUyREFhcGVHZHFtWDVO
      ZWs0YzFuQ1NDT04zQ3FNRWRFb1NPTjhjcE11bjIzZ2MyU3IyU0QvNml2bGZUbjJHCmpCdUY3L1NL
      UlFGM3JsRktsWnNNVmVidjJLREkrVkRxMzZjTERHbXB5eWxtRjkzSkNzbkI4Q2ZuWmUxNS9GR1cK
      Y09lNGUrZ0ZtQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admin_tls_key: >
      LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
      QVNDQ1N3d2dna29BZ0VBQW9JQ0FRRGZ3aG0razltbHgrM2oKSVZsYlhqRlR0V2VjZW9OUmRPNWNZ
      K2pyeURJMU5tVzhaMFlvOHcwbitxNnBuU053QmhaU0VZU1MvcnF6K2NFcAp1NVloTmFWVnVuUmZ5
      Qjk4dkRXbHNDZkkyZjhZejExMVhiUkZBZkEyMUl5ekRkTkQxWCtjSitXZFhFc0FQbkk2CjJEQ21B
      Vk1VMTZUMWdWK1EzNUduZlRFZmR6RjMrTklxa3BWYXpqbkNXQ3lHR0tFVU9ybDdNV0J4RFM5ZzQ3
      Z0cKTmhGN0ZMRk5ycEEvYnI3eUdmMU03UEhNMFVRSFRtTjB3NW5kN2VxU0cwcWEzWW9OTG5TU2xL
      Z1Y0YzVOWm1lLwpUMWhqOE1sdTZESkd6ejlTY24yTE04azZxN1gyRCttSmNsMnVXRTlkQy9weVRs
      bnhoRGlUbThPSVZaeEphaGVrClU5VHVwb3lKdkFvZm1XMWxNejJMdWdwZGt3R3BEc3BieGwzbzFM
      U3RkK09hNjVvY2V1RDhxaUtqS2hYT3pmdFgKQzZFUnNSam1QVXF4dWE4OW9iSHdBMWh0ZlhyTUtH
      Vk82RUsrUDBaQ0FqdlFiR1JYUVZuU1JIUUFCcFAzV3ZDaQp2Q0ZybWdCOGZSR0RuaVZqRWtDYWNO
      TGxLcjVaV1prS21leXdqM1ZTUU1JZEErSlJ4cFFQV09OWW9yemd4KzJXClBKa3A1Zmp1NjhDSG5t
      MFlXcEVSOTM2TU55ZkYzVWtmTzRYWlpSUlVBSGRSVVM0NDRvelN3TXZ2Nkw5UlZjWDEKSmtHWFJ4
      UWJNNC81RzVJT0xucWFGR1pvSnFHaFRMUWRpbzI5dGNGbUIrVytteVZ3TVZCRmx1WTc1ZGV0SFRm
      MQp1ZnZheEl0OUFVUUtuMi9POHJ0VHMxTGgwRVlLcFFJREFRQUJBb0lDQUJ2cjZxNS9ZSjl4VFZ3
      VVkwUWxndDVCCk9zYXArdzBGSEdGbkRqK3Q0YVlHUGJlKzQyQmt3L1dETUp4MXdXQlBRaVhIamRX
      Ujk5WlJpaXNjLzJUeGZzb3QKMUN2SG16WkRmaVpJenc0Zk5kZnd1R2JXNUpIZjVndlJoaVVweW4w
      aWZTUU5UbmZPZG9WM1JXWFdhR3V1cXFGbApMMjU3VUdPUm9tbFdFL1VyT0g4U0M1ZkladDdIOFNr
      eE80MFlNYkdHaW5LMi9LUGUwMVN4MWRyZ2tGbmRnU3FDClovbWlaaTFyMU5IdWwxWEpuMFdTSUpN
      SGZZSFdHSGxXOG41VXVzOWVScW1yNXpXajBjeVN4TXQ0cVR6L1pRTnoKOGlJbjVtenhZSDBvWHlu
      MUYyVzNJcHRHTEM1L1VwZjMwSzdHM0M1cEkyNDM5N1JoaW5rV3hoQjViWTdDTmJNVwpmZDJoZUo3
      cS9SOE83dmRZVzRsRk9zOXMySE44UER1ZTNJZ3ozVDRZVnU0K0I2R0l2dERKeHJFQ0tzZHNjWWhC
      CjFXSUQ2K2JTOVNNNnJHOU9iS2pSU1pOTDh0UTQwL3ZwOWdpR3RndldCTFFLZmNqenFzQTZ1REp5
      aE5rTjd1YSsKR1pxZEY5M0oyUnBGZmhSVk11Z3UraFlCT3lzU2NCYW5vNHVwUTlTRWlDbVNMMGp3
      Y3k0ZnBJNkdhK1RHUFF2dgpUbGlTbG5ONjJiRnBmOFlaWHM0elV6RnhDdnVzUTdrQXo5VXRYTCtW
      UGZYVWdLc3luOGF2REZaMythOVV6c1VCClprcEVuS2FvbC8rNmU3RzUyQjgrdHVnTVYwNUFrRmlt
      OGRucVc3WkJHTHZpSEhpNHF6WDdOVjJRdmlzdzFvZnYKek8yN2xYSng1YWZwWUQ3bFFpdkJBb0lC
      QVFENVJjRllQVjVxYjU1cm1CcFFyV21UVExJa3F1MlNUYnZnRHNtcApYN1pHYld1RlFCUGI0VjJU
      TUo1OW1kcUFIYTNMNG1IOW10eEROUGU1am4xaWluR2twRzdiWHYrYTlTS3R5WVRzCkx0WUltVk55
      VlFlZWhWYjVTVWE4dk5OdlNKV1p5SkY1QU8vNXdKVVo1dEtNYlZSY2JtREI3SVo4dWNEVUl1TVcK
      T21CbEZlRlhwbFpvc2E4cnhxQVVJb09ENzJ6WHl1UHUwOTNka2dvcmgxTFFlVlV2VmlWbkxPQlVa
      cUJjRkNYdgo3MUR0V25UMXFvZmZIdlZCMVBidWhvbm11eFB0NVFRUHAwWDV6TFdwK2x2cHRxTEpM
      T21xZG4ycmkwRUFRdURKCldpbkNVVnprYlRYVzlGV29lOGFYMEVoeFhwUlBJNWNpWVRGWjJZK2pD
      RDRLeVY3OUFvSUJBUURsekJDa2lYck8Kc0MvckpwL3dTVTJya2cxUUVFRnJtem1lbG8yQmFudVJJ
      K21qNnlhTlhVYlRnYkpVYjdndm92dzhJK01DRTZzWAozbUZwU21oNHVhaW1YTitnZzFNWUFoYlJL
      VWVva3BXUkl0bGdMb09wWFpQQVhXSk1hKzdLWGhveHVIMDhhc3JSCkthNmNONVVOSjVmT1ZBUVU4
      WEUxQVVjdVVsM202UStiMGtIM01jUlJGRkVEVHFZdHBaRlh4bk5hc2xjMnJDSTMKOTNKaER2Y0Fl
      bjFpZHMxZkFqMWtseit0WUdwRE1scm5rQTQwbTQvZ3RxdGdDaDBTdWFKTmtBRFJmY1B2TnQ5VQox
      ck94UDZja1lYbWlzNkUxOGZyOUM1aXY2SFZpYllpRmNOS3lGZ1FVNW9Pa3RtWnBmT1p2NjdYNVNL
      alFTWmNyClVRWkZBSEVqVFM3SkFvSUJBQXB3MG9WWXBMQytsaHNabHRpVU90elJsSkNXbkRiSmpM
      bjR4SmVVaTdUdGRsaHgKYzZOOUVBZFBQUVF6d29RbE9oZFZGeGVoT2VLU3dHR0VSMW91UkU1S0dO
      NlZYdzFsZ1J0WVdubnVDRWI1N1JYWAoyK2JXM09xNkYvMWx4MUZjNys4dUNISFNDVHNqeHRyNzRR
      dkN0SXJla0t6dXREOWJKR2wrUUphNHdUcmFyTUtZCkUveDBuTXF2bWhyZHl6Wm1lOStaL3V3TThi
      a0xHZVB5MmhRalVOOFhzNTlic05XNEtyVlFucm9yQXUrK0h6SCsKLzR2bjV3dm4yS1BxL0xHdVdr
      cFhrbEQ1aDZQTDREd0xZWGdyanl2djlxV09LdnRaYk5LTytvMVVlblZLSlNMbwpOQjRadzlDM3hu
      eXJXNjFyOGJoUzNFeXpWM2JVOXdBMEl5MGVmQjBDZ2dFQkFMK2MzQmZHeDA5SFhIMlE5SFpSCk9X
      R2g1RlhwYUJPSkdJK2piQlVJckVhSEVvL3JTWGRBMndrTU1aMzBsam1xaHZiQzJjeG1pQmpjQm8v
      Y1NxYTMKOE9mZnMxek5oR0VWaE44ZHM3SGRvTGVudm1oVUFOY2R2MUQ4elRWNkhtQkIvVWVPVldj
      bWlUM0ZxdUo1K21CQQpybldPV3VUM3VuVC9QdEppUGdpSU44cXZsTy9CWUxoVzM0S0pkMG5Dc0NI
      bnlWSk1PU3JPZDY0Qk9DKzBZY1BWClgyM1dNRU5Udzh0M3p0SUwvaTlQOHJyNXhNNmJGR3JGQnJ1
      TFUxakV6NUFyVG5OZ2todUt2c2lvU3FlMnN2RkUKRWovWDFzbjduMVNXOGRka1YxVWVqbUx1ZzlH
      WlNBZ0JlcTNDcGp5NXVCQ0ZGSFRyNEUvbHZSYVNkazdkSW5uVQpKdmtDZ2dFQURTdjZsSUdpNVBC
      OHVYZDQxY29UdGhQeWtKcVYyZFRIcnpxTENpOGpvRm1DaTgwN2VrTHlSM2p6ClRhMDgxYWYyM2xW
      VTNwQzZqS0h2R0hoMk9ta0VMakhqY0J4ak5lRy9TdzZXaVhtWFA2UGZsSGFhWGY5cFdKWmkKU0VC
      c0VmcHNuTCtIdXVidHRQS004WkQwMHZVZFc4RTM5ZGZ5dFVsRXY5UTZhTnZJcTBQNmFYWEZZSkd3
      MGtVWQo2RjVrTFFieUkzQXNEcjZhVnlMWVNQajVtRmtOeGRCRGo3N056eG1ITW4rK2hldlVOTENH
      STdFMWxBWHBCRDBvCk5ON1Zsek1NWXluMFhsYndqVEpBbUFrT3A4VDZJZE1VVXVqNkVucDFCZi9l
      c1I3bDBYNU9mZ0RXWUY1ZlJpdi8KNUZ0VHM1Z1dkNklvQXA2dmRIU1NBQVRweS96eW5BPT0KLS0t
      LS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
    tenant_tls_cert: >
      ZExFSnBBOU52QlZNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1CWXgKRkRBU0JnTlZCQU1NQ3lvdWRXUnpM
      bXh2WTJGc01CNFhEVEkwTURjeE1ERTVNekExTUZvWERUSTFNRGN4TURFNQpNekExTUZvd0ZqRVVN
      QklHQTFVRUF3d0xLaTUxWkhNdWJHOWpZV3d3Z2dJaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUNE
      d0F3Z2dJS0FvSUNBUURmd2htK2s5bWx4KzNqSVZsYlhqRlR0V2VjZW9OUmRPNWNZK2pyeURJMU5t
      VzgKWjBZbzh3MG4rcTZwblNOd0JoWlNFWVNTL3JxeitjRXB1NVloTmFWVnVuUmZ5Qjk4dkRXbHND
      ZkkyZjhZejExMQpYYlJGQWZBMjFJeXpEZE5EMVgrY0orV2RYRXNBUG5JNjJEQ21BVk1VMTZUMWdW
      K1EzNUduZlRFZmR6RjMrTklxCmtwVmF6am5DV0N5R0dLRVVPcmw3TVdCeERTOWc0N2dHTmhGN0ZM
      Rk5ycEEvYnI3eUdmMU03UEhNMFVRSFRtTjAKdzVuZDdlcVNHMHFhM1lvTkxuU1NsS2dWNGM1Tlpt
      ZS9UMWhqOE1sdTZESkd6ejlTY24yTE04azZxN1gyRCttSgpjbDJ1V0U5ZEMvcHlUbG54aERpVG04
      T0lWWnhKYWhla1U5VHVwb3lKdkFvZm1XMWxNejJMdWdwZGt3R3BEc3BiCnhsM28xTFN0ZCtPYTY1
      b2NldUQ4cWlLaktoWE96ZnRYQzZFUnNSam1QVXF4dWE4OW9iSHdBMWh0ZlhyTUtHVk8KNkVLK1Aw
      WkNBanZRYkdSWFFWblNSSFFBQnBQM1d2Q2l2Q0ZybWdCOGZSR0RuaVZqRWtDYWNOTGxLcjVaV1pr
      SwptZXl3ajNWU1FNSWRBK0pSeHBRUFdPTllvcnpneCsyV1BKa3A1Zmp1NjhDSG5tMFlXcEVSOTM2
      TU55ZkYzVWtmCk80WFpaUlJVQUhkUlVTNDQ0b3pTd012djZMOVJWY1gxSmtHWFJ4UWJNNC81RzVJ
      T0xucWFGR1pvSnFHaFRMUWQKaW8yOXRjRm1CK1crbXlWd01WQkZsdVk3NWRldEhUZjF1ZnZheEl0
      OUFVUUtuMi9POHJ0VHMxTGgwRVlLcFFJRApBUUFCTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElDQVFC
      ZVp2cDM0NElqWlN4eWR3S0c1L3UxT0tqU0ZLSnA5eHhTCm1OWjBNQnpDNjdUZWJTMzR6NlRKZWZU
      UmxWVndOYXR2LzhVSkhGYlVnL2xQTi9vTGpXSFJtRkNwUE1yNWJoYnYKV2dneGRHM2thZ29HRHVM
      MlZhYjhPRTJNRTJwSDJkZDBLL0VxbEo3OEJQNHBDOFpTL3Yxc1Y4QlRDYVQrNWlUMgpFVjR4Q2VD
      cnk3N3Yrczl1TUZPRzBHbHlmVkluQU4xSlk4cXQyMVFJR3pyTCtrQndoaHFVaS8wY1hDTUxjUWgw
      ClRHYk5PY0RZV2kxdHhjSHE0SzZ0YkI4M2crM2JjZ25SeitubkltMEpXR1h6OTVsTGNFdjZpUzVq
      ZVNBb2oyaXQKK0E4dHAyWnFId1lic0JUVDBEbmJ5b1hJVFg1dllOYkZoWHM5cm1qNWFTUGdaM1Qx
      WGFPdittMXJYbm92MXBzaAo5YytEQWpDRHVnZDJ4OUlpZzFOSVVCQndwUDVGS1QyMFlEWG41Rlp5
      N2JkdzBzdldyL2x3azBSeVNFQzdIRTBjClNKNnJCU0RBbVB1VHRmaElPVERMVWY4STZib2VUeCs5
      Mmk3OCt2aklXZ1gzUEZtY1ZZOVY3RUVycGR0dmtnc2YKL2s3NDRhWVd0L0IxNy9NeFlIV2RUS0ZW
      c2U1bXB3SWErK1djbTVnS3VSVTRRUWM3MTBjNE94bDF2OE15T0Z3ZgpvYlUyREFhcGVHZHFtWDVO
      ZWs0YzFuQ1NDT04zQ3FNRWRFb1NPTjhjcE11bjIzZ2MyU3IyU0QvNml2bGZUbjJHCmpCdUY3L1NL
      UlFGM3JsRktsWnNNVmVidjJLREkrVkRxMzZjTERHbXB5eWxtRjkzSkNzbkI4Q2ZuWmUxNS9GR1cK
      Y09lNGUrZ0ZtQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tenant_tls_key: >
      LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
      QVNDQ1N3d2dna29BZ0VBQW9JQ0FRRGZ3aG0razltbHgrM2oKSVZsYlhqRlR0V2VjZW9OUmRPNWNZ
      K2pyeURJMU5tVzhaMFlvOHcwbitxNnBuU053QmhaU0VZU1MvcnF6K2NFcAp1NVloTmFWVnVuUmZ5
      Qjk4dkRXbHNDZkkyZjhZejExMVhiUkZBZkEyMUl5ekRkTkQxWCtjSitXZFhFc0FQbkk2CjJEQ21B
      Vk1VMTZUMWdWK1EzNUduZlRFZmR6RjMrTklxa3BWYXpqbkNXQ3lHR0tFVU9ybDdNV0J4RFM5ZzQ3
      Z0cKTmhGN0ZMRk5ycEEvYnI3eUdmMU03UEhNMFVRSFRtTjB3NW5kN2VxU0cwcWEzWW9OTG5TU2xL
      Z1Y0YzVOWm1lLwpUMWhqOE1sdTZESkd6ejlTY24yTE04azZxN1gyRCttSmNsMnVXRTlkQy9weVRs
      bnhoRGlUbThPSVZaeEphaGVrClU5VHVwb3lKdkFvZm1XMWxNejJMdWdwZGt3R3BEc3BieGwzbzFM
      U3RkK09hNjVvY2V1RDhxaUtqS2hYT3pmdFgKQzZFUnNSam1QVXF4dWE4OW9iSHdBMWh0ZlhyTUtH
      Vk82RUsrUDBaQ0FqdlFiR1JYUVZuU1JIUUFCcFAzV3ZDaQp2Q0ZybWdCOGZSR0RuaVZqRWtDYWNO
      TGxLcjVaV1prS21leXdqM1ZTUU1JZEErSlJ4cFFQV09OWW9yemd4KzJXClBKa3A1Zmp1NjhDSG5t
      MFlXcEVSOTM2TU55ZkYzVWtmTzRYWlpSUlVBSGRSVVM0NDRvelN3TXZ2Nkw5UlZjWDEKSmtHWFJ4
      UWJNNC81RzVJT0xucWFGR1pvSnFHaFRMUWRpbzI5dGNGbUIrVytteVZ3TVZCRmx1WTc1ZGV0SFRm
      MQp1ZnZheEl0OUFVUUtuMi9POHJ0VHMxTGgwRVlLcFFJREFRQUJBb0lDQUJ2cjZxNS9ZSjl4VFZ3
      VVkwUWxndDVCCk9zYXArdzBGSEdGbkRqK3Q0YVlHUGJlKzQyQmt3L1dETUp4MXdXQlBRaVhIamRX
      Ujk5WlJpaXNjLzJUeGZzb3QKMUN2SG16WkRmaVpJenc0Zk5kZnd1R2JXNUpIZjVndlJoaVVweW4w
      aWZTUU5UbmZPZG9WM1JXWFdhR3V1cXFGbApMMjU3VUdPUm9tbFdFL1VyT0g4U0M1ZkladDdIOFNr
      eE80MFlNYkdHaW5LMi9LUGUwMVN4MWRyZ2tGbmRnU3FDClovbWlaaTFyMU5IdWwxWEpuMFdTSUpN
      SGZZSFdHSGxXOG41VXVzOWVScW1yNXpXajBjeVN4TXQ0cVR6L1pRTnoKOGlJbjVtenhZSDBvWHlu
      MUYyVzNJcHRHTEM1L1VwZjMwSzdHM0M1cEkyNDM5N1JoaW5rV3hoQjViWTdDTmJNVwpmZDJoZUo3
      cS9SOE83dmRZVzRsRk9zOXMySE44UER1ZTNJZ3ozVDRZVnU0K0I2R0l2dERKeHJFQ0tzZHNjWWhC
      CjFXSUQ2K2JTOVNNNnJHOU9iS2pSU1pOTDh0UTQwL3ZwOWdpR3RndldCTFFLZmNqenFzQTZ1REp5
      aE5rTjd1YSsKR1pxZEY5M0oyUnBGZmhSVk11Z3UraFlCT3lzU2NCYW5vNHVwUTlTRWlDbVNMMGp3
      Y3k0ZnBJNkdhK1RHUFF2dgpUbGlTbG5ONjJiRnBmOFlaWHM0elV6RnhDdnVzUTdrQXo5VXRYTCtW
      UGZYVWdLc3luOGF2REZaMythOVV6c1VCClprcEVuS2FvbC8rNmU3RzUyQjgrdHVnTVYwNUFrRmlt
      OGRucVc3WkJHTHZpSEhpNHF6WDdOVjJRdmlzdzFvZnYKek8yN2xYSng1YWZwWUQ3bFFpdkJBb0lC
      QVFENVJjRllQVjVxYjU1cm1CcFFyV21UVExJa3F1MlNUYnZnRHNtcApYN1pHYld1RlFCUGI0VjJU
      TUo1OW1kcUFIYTNMNG1IOW10eEROUGU1am4xaWluR2twRzdiWHYrYTlTS3R5WVRzCkx0WUltVk55
      VlFlZWhWYjVTVWE4dk5OdlNKV1p5SkY1QU8vNXdKVVo1dEtNYlZSY2JtREI3SVo4dWNEVUl1TVcK
      T21CbEZlRlhwbFpvc2E4cnhxQVVJb09ENzJ6WHl1UHUwOTNka2dvcmgxTFFlVlV2VmlWbkxPQlVa
      cUJjRkNYdgo3MUR0V25UMXFvZmZIdlZCMVBidWhvbm11eFB0NVFRUHAwWDV6TFdwK2x2cHRxTEpM
      T21xZG4ycmkwRUFRdURKCldpbkNVVnprYlRYVzlGV29lOGFYMEVoeFhwUlBJNWNpWVRGWjJZK2pD
      RDRLeVY3OUFvSUJBUURsekJDa2lYck8Kc0MvckpwL3dTVTJya2cxUUVFRnJtem1lbG8yQmFudVJJ
      K21qNnlhTlhVYlRnYkpVYjdndm92dzhJK01DRTZzWAozbUZwU21oNHVhaW1YTitnZzFNWUFoYlJL
      VWVva3BXUkl0bGdMb09wWFpQQVhXSk1hKzdLWGhveHVIMDhhc3JSCkthNmNONVVOSjVmT1ZBUVU4
      WEUxQVVjdVVsM202UStiMGtIM01jUlJGRkVEVHFZdHBaRlh4bk5hc2xjMnJDSTMKOTNKaER2Y0Fl
      bjFpZHMxZkFqMWtseit0WUdwRE1scm5rQTQwbTQvZ3RxdGdDaDBTdWFKTmtBRFJmY1B2TnQ5VQox
      ck94UDZja1lYbWlzNkUxOGZyOUM1aXY2SFZpYllpRmNOS3lGZ1FVNW9Pa3RtWnBmT1p2NjdYNVNL
      alFTWmNyClVRWkZBSEVqVFM3SkFvSUJBQXB3MG9WWXBMQytsaHNabHRpVU90elJsSkNXbkRiSmpM
      bjR4SmVVaTdUdGRsaHgKYzZOOUVBZFBQUVF6d29RbE9oZFZGeGVoT2VLU3dHR0VSMW91UkU1S0dO
      NlZYdzFsZ1J0WVdubnVDRWI1N1JYWAoyK2JXM09xNkYvMWx4MUZjNys4dUNISFNDVHNqeHRyNzRR
      dkN0SXJla0t6dXREOWJKR2wrUUphNHdUcmFyTUtZCkUveDBuTXF2bWhyZHl6Wm1lOStaL3V3TThi
      a0xHZVB5MmhRalVOOFhzNTlic05XNEtyVlFucm9yQXUrK0h6SCsKLzR2bjV3dm4yS1BxL0xHdVdr
      cFhrbEQ1aDZQTDREd0xZWGdyanl2djlxV09LdnRaYk5LTytvMVVlblZLSlNMbwpOQjRadzlDM3hu
      eXJXNjFyOGJoUzNFeXpWM2JVOXdBMEl5MGVmQjBDZ2dFQkFMK2MzQmZHeDA5SFhIMlE5SFpSCk9X
      R2g1RlhwYUJPSkdJK2piQlVJckVhSEVvL3JTWGRBMndrTU1aMzBsam1xaHZiQzJjeG1pQmpjQm8v
      Y1NxYTMKOE9mZnMxek5oR0VWaE44ZHM3SGRvTGVudm1oVUFOY2R2MUQ4elRWNkhtQkIvVWVPVldj
      bWlUM0ZxdUo1K21CQQpybldPV3VUM3VuVC9QdEppUGdpSU44cXZsTy9CWUxoVzM0S0pkMG5Dc0NI
      bnlWSk1PU3JPZDY0Qk9DKzBZY1BWClgyM1dNRU5Udzh0M3p0SUwvaTlQOHJyNXhNNmJGR3JGQnJ1
      TFUxakV6NUFyVG5OZ2todUt2c2lvU3FlMnN2RkUKRWovWDFzbjduMVNXOGRka1YxVWVqbUx1ZzlH
      WlNBZ0JlcTNDcGp5NXVCQ0ZGSFRyNEUvbHZSYVNkazdkSW5uVQpKdmtDZ2dFQURTdjZsSUdpNVBC
      OHVYZDQxY29UdGhQeWtKcVYyZFRIcnpxTENpOGpvRm1DaTgwN2VrTHlSM2p6ClRhMDgxYWYyM2xW
      VTNwQzZqS0h2R0hoMk9ta0VMakhqY0J4ak5lRy9TdzZXaVhtWFA2UGZsSGFhWGY5cFdKWmkKU0VC
      c0VmcHNuTCtIdXVidHRQS004WkQwMHZVZFc4RTM5ZGZ5dFVsRXY5UTZhTnZJcTBQNmFYWEZZSkd3
      MGtVWQo2RjVrTFFieUkzQXNEcjZhVnlMWVNQajVtRmtOeGRCRGo3N056eG1ITW4rK2hldlVOTENH
      STdFMWxBWHBCRDBvCk5ON1Zsek1NWXluMFhsYndqVEpBbUFrT3A4VDZJZE1VVXVqNkVucDFCZi9l
      c1I3bDBYNU9mZ0RXWUY1ZlJpdi8KNUZ0VHM1Z1dkNklvQXA2dmRIU1NBQVRweS96eW5BPT0KLS0t
      LS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
