replicaCount: 1
commonLabels: {}

imagePullPolicy: IfNotPresent

# TODO: renovate setup
localPathProvisioner:
  image: ###ZARF_REGISTRY###/rancher/local-path-provisioner:v0.0.26

  # TODO: renovate setup
helperPod:
  image: ###ZARF_REGISTRY###/chainguard/busybox:latest

imagePullSecrets:
  - name: private-registry

## For creating the StorageClass automatically:
storageClass:
  create: true

  ## Set StorageClass as the default StorageClass
  ## Ignored if storageClass.create is false
  defaultClass: ###ZARF_VAR_IS_DEFAULT_STORAGECLASS###

  ## The default volume type this storage class creates, can be "local" or "hostPath"
  defaultVolumeType: ###ZARF_VAR_VOLUME_TYPE###

  ## Set a StorageClass name
  ## Ignored if storageClass.create is false
  name: local-path

  ## ReclaimPolicy field of the class, which can be either Delete or Retain
  reclaimPolicy: Retain

  ## volumeBindingMode field controls when volume binding and dynamic provisioning should occur, can be  "Immediate" or "WaitForFirstConsumer"
  volumeBindingMode: WaitForFirstConsumer

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
  runAsUser: 65534
  runAsGroup: 65534
  readOnlyRootFilesystem: true

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

rbac:
  # Specifies whether RBAC resources should be created
  create: true

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

nodeSelector: {}

tolerations: []

affinity: {}

configmap:
  # specify the config map name
  name: local-path-config
  # specify the custom script for setup and teardown
  setup: |-
    #!/bin/sh

    set -eu

    # Function to check mount point and print remaining space
    check_mount() {
        local dir="$1"
        if [ -d "$dir" ]; then
            # Get permissions and owner information
            permissions=$(ls -ld "$dir" | awk '{print $1}')
            owner=$(ls -ld "$dir" | awk '{print $3":"$4}')
            echo "Mount Point: $dir"
            echo "Permissions: $permissions"
            echo "Owner/Group: $owner"

            # Check if the owner is the current user
            current_user=$(whoami)
            if [ "$owner" != "$current_user:$current_user" ]; then
                # Attempt to modify permissions using sudo chown
                sudo chown "$current_user:$current_user" "$dir"
                echo "Permissions modified using sudo chown"
            else
                echo "Directory is already owned by $current_user"
            fi

            # Recursively check parent directories
            parent_dir=$(dirname "$dir")
            if [ "$parent_dir" != "$dir" ]; then
                check_mount "$parent_dir"
            fi
        else
            echo "Mount Point $dir does not exist"
            echo "Creating Volume Directory in $dir..."
            mkdir -m 0777 -p "$dir"
            check_mount "$dir"
        fi
    }

    # Check if mount point was provided as an argument
    if [ -z "$VOL_DIR" ]; then
        echo "VOL_DIR was not specified"
        exit 1
    else
        check_mount "$VOL_DIR"
    fi

  teardown: |-
    #!/bin/sh

    set -eu

    sudo rm -rf "$VOL_DIR"

# Number of provisioner worker threads to call provision/delete simultaneously.
# workerThreads: 4

# Number of retries of failed volume provisioning. 0 means retry indefinitely.
# provisioningRetryCount: 15

# Number of retries of failed volume deletion. 0 means retry indefinitely.
# deletionRetryCount: 15
