apiVersion: uds.dev/v1alpha1
kind: Exemption
metadata:
  name: nvidia-gpu-operator
  namespace: uds-policy-exemptions
spec:
  exemptions:
    - policies:
        - DisallowHostNamespaces
        - DisallowPrivileged
        - RequireNonRootUser
        - DropAllCapabilities
        - RestrictHostPathWrite
        - RestrictVolumeTypes
        - RestrictCapabilities
        - RestrictHostPorts
      matcher:
        namespace: "nvidia-gpu-operator"
        name: ".*"
      title: "all pods"
      description: "Exempt NVIDIA GPU Operator from policy enforcement"
