apiVersion: uds.dev/v1alpha1
kind: Exemption
metadata:
  name: uds-rke2-infrastructure
  namespace: uds-policy-exemptions
spec:
  exemptions:
    - policies:
        - DisallowHostNamespaces
        - DisallowPrivileged
        - RequireNonRootUser
        - DropAllCapabilities
        - RestrictHostPathWrite
        - RestrictVolumeTypes
        - RestrictCapabilities
        - RestrictHostPorts
      matcher:
        namespace: "uds-rke2-infrastructure"
        name: ".*"
      title: "all pods"
      description: "Exempt UDS RKE2 infrastructure from policy enforcement"