apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-address-pool
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
    {{- $baseIP := .Values.baseIP }}
    {{- range $pool := splitList ", " .Values.ipAddressPool }}
    - {{ printf "%s.%s/32" $baseIP $pool }}
    {{- end }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: {{ .Release.Namespace }}
spec:
  interfaces:
    {{- range $interface := splitList ", " .Values.interfaces }}
    - {{ $interface | trim }}
    {{- end }}
