apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-address-pool
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
    - {{ .Values.ipAddressPool }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: {{ .Release.Namespace }}
spec:
  interfaces:
    - {{ .Values.interface }}
