apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "local-path-provisioner.labels" . | indent 4 }}
data:
  config.json: |-
    {
      "nodePathMap": [
        {{- range $nodePathMap := .Values.nodePathMap }}
        {
          "node": "{{ $nodePathMap.node }}",
          "paths": [
            {{- range $path := $nodePathMap.paths }}
            "{{ $path }}"{{ if not $last }},{{ end }}
            {{- end }}
          ]
        }{{ if not $last }},{{ end }}
        {{- end }}
      ]
    }
  setup: |-
    {{- .Values.configmap.setup | nindent 4 }}
  teardown: |-
    {{- .Values.configmap.teardown | nindent 4 }}
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      priorityClassName: system-node-critical
      tolerations:
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
      containers:
        - name: helper-pod
          image: {{ .Values.helperPod.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
