apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "local-path-provisioner.labels" . | indent 4 }}
data:
  config.json: |-
    {{- $config := dict }}
    {{- with .Values.nodePathMap }}
    {{- $config = set $config "nodePathMap" . }}
    {{- end }}
    {{- with .Values.sharedFileSystemPath }}
    {{- $config = set $config "sharedFileSystemPath" . }}
    {{- end }}
    {{- with .Values.storageClassConfigs }}
    {{- $configs := dict }}
    {{- range $key, $value := . }}
      {{- $configValue := dict }}
      {{- with $value.nodePathMap }}
      {{- $configValue = set $configValue "nodePathMap" . }}
      {{- end }}
      {{- with $value.sharedFileSystemPath }}
      {{- $configValue = set $configValue "sharedFileSystemPath" . }}
      {{- end }}
      {{- $configs = set $configs $key $configValue }}
    {{- end }}
    {{- $config = set $config "storageClassConfigs" $configs }}
    {{- end }}
    {{- $config | toPrettyJson | nindent 4 }}
  setup: |-
    {{- .Values.configmap.setup | nindent 4 }}
  teardown: |-
    {{- .Values.configmap.teardown | nindent 4 }}
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      priorityClassName: system-node-critical
      tolerations:
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
      containers:
        - name: helper-pod
          env:
            - name: VOL_DIR
              value: {{ .Values.configmap.helperPod.env.volDir }}
          image: {{ .Values.helperImage.repository }}:{{ .Values.helperImage.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
