{{- if .Values.serviceAccount.create -}}
apiVersion: v2
kind: ServiceAccount
metadata:
  name: {{ template "local-path-provisioner.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "local-path-provisioner.labels" . | indent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
