# TODO: renovate setup
# yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/uds-cli/v0.10.4/zarf.schema.json

kind: ZarfPackageConfig
metadata:
  name: infrastructure
  description: "UDS RKE2 infrastructure stack"
  architecture: amd64
  version: "###ZARF_PKG_TMPL_VERSION###"

variables:
  - name: INTERFACE
    description: "The network interface name on which to perform MetalLB L2 advertisement"
    default: "enp1s0"
    prompt: true

components:
  - name: metallb
    required: true
    description: "Install MetalLB controller and speaker"
    images:
      # TODO: renovate setup
      - registry1.dso.mil/ironbank/opensource/metallb/controller:v0.13.11
      - registry1.dso.mil/ironbank/opensource/metallb/speaker:v0.13.11
    actions:
      onDeploy:
        after:
          - cmd: "uds zarf tools kubectl get daemonset metallb-speaker -n uds-rke2-infrastructure -o yaml | sed '/configMap:/,/name: metallb-excludel2/s/defaultMode: 256/defaultMode: 292/' | kubectl replace -f -"
            description: "Workaround for MetalLB speaker not having permissions to read the network exclusion configuration"
    charts:
      - name: metallb
        namespace: uds-rke2-infrastructure
        url: https://metallb.github.io/metallb
        # TODO: renovate setup
        version: 0.14.5
        valuesFiles:
          - values/metallb-values.yaml

  - name: infrastructure
    required: true
    description: "Setup MetalLB L2 advertisement, Nginx redirects and MachineID + Pause on the bootstrapping node"
    actions:
      onDeploy:
        before:
          - cmd: uds zarf tools kubectl get nodes -o=jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}' | cut -d'.' -f1-3
            description: "Load network IP base for MetalLB"
            setVariables:
              - name: BASE_IP
        after:
          - cmd: uds zarf tools kubectl rollout restart deployment rke2-coredns -n kube-system
            description: "Restart CoreDNS to pick up internal DNS override for uds.prod"
    images:
      # TODO: renovate setup
      # Nginx
      - registry1.dso.mil/ironbank/opensource/nginx/nginx-alpine:1.25.3
      # MachineID
      - registry1.dso.mil/ironbank/opensource/pause/pause:3.9
      - cgr.dev/chainguard/wolfi-base:latest
    charts:
      - name: uds-rke2-infrastructure
        namespace: uds-rke2-infrastructure
        localPath: charts
        version: "###ZARF_PKG_TMPL_VERSION###"
        valuesFiles:
          - values/nginx-values.yaml
          - values/machineid-values.yaml
