name: Test UDS Capability

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
    paths:
      - "packages/init"
      - "packages/uds-rke2"
      - "tasks"
      - ".github/workflows/build-test.yaml"
      - "tasks.yaml"

concurrency:
  group: build-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-clean-install:
    runs-on: ubuntu-latest
    name: Test Build and Install

    permissions:
      id-token: write
      contents: write
      packages: write

    steps:
      - name: Maximize Build Space
        uses: easimon/maximize-build-space@fc881a613ad2a34aca9c9624518214ebc21dfc0c # v10
        with:
          remove-android: "true"
          remove-dotnet: "true"
          remove-codeql: "true"
          remove-docker-images: "true"
          remove-large-packages: "true"
          remove-cached-tools: "true"
          remove-swap-file: "true"

      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup UDS
        if: always()
        uses: ./.github/actions/setup
        with:
          registry1Username: ${{secrets.IRON_BANK_ROBOT_USERNAME}}
          registry1Password: ${{secrets.IRON_BANK_ROBOT_PASSWORD}}
          ghToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Test the UDS RKE2 Local-Path Bootstrap
        run: |
          du -h / || true
          sudo uds run uds-rke2-local-path --no-progress --log-level warn -a amd64
