name: Test UDS Capability

on:
  push:
    branches:
      - "main"
  # TODO: remove the ignore-all later
  pull_request:
      branches:
        - "main"
      paths:
        - "bundles"
        - "packages"
        - "tasks"
        - ".github/workflows/build-test.yaml"
        - "tasks.yaml"

permissions:
  id-token: write
  contents: read

concurrency:
  group: build-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-clean-install:
    runs-on: ubuntu-latest
    name: Test Build and Install

    steps:
      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup UDS
        if: always()
        uses: ./.github/actions/setup
        with:
          registry1Username: ${{secrets.IRON_BANK_ROBOT_USERNAME}}
          registry1Password: ${{secrets.IRON_BANK_ROBOT_PASSWORD}}
          ghToken: ${{ secrets.GITHUB_TOKEN }}

      # - name: Test the UDS RKE2 Bootstrap
      #   run: sudo uds run uds-rke2 --no-progress --log-level warn -a amd64

      - name: Test the UDS RKE2 Local Path Bundle
        run: sudo uds run local-path-bootstrap -a amd64 --set CREATE_OPTIONS="--confirm" --set DEPLOY_OPTIONS="--confirm"
