name: Test UDS Capability

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
    paths:
      - "packages/init"
      - "packages/uds-rke2"
      - "tasks"
      - ".github/workflows/build-test.yaml"
      - "tasks.yaml"

concurrency:
  group: build-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-clean-install:
    runs-on: ubuntu-latest
    name: Test Build and Install

    permissions:
      id-token: write
      contents: write
      packages: write

    steps:
      - name: Maximize build space
        uses: justinthelaw/maximize-github-runner-space@v0.1.1 # v0.1.1
        with:
          # Standard package removal actions
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"
          # Custom removal actions
          remove-large-packages: "true"
          remove-swapfile: "true"
          remove-cached-tools: "true"

      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup UDS
        if: always()
        uses: ./.github/actions/setup
        with:
          registry1Username: ${{secrets.IRON_BANK_ROBOT_USERNAME}}
          registry1Password: ${{secrets.IRON_BANK_ROBOT_PASSWORD}}
          ghToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create /opt/uds LVM
        run: |
          sudo mkdir -p /opt/uds
          sudo chown -Rv 65534:65534 /opt/uds

      - name: Test the UDS RKE2 Local-Path Bootstrap
        run: |
          sudo uds run uds-rke2-local-path-test --no-progress --log-level warn -a amd64
