name: Validate Labels

on:
  push:
    branches:
      - '!main'
  pull_request:
    branches: [main]
    types: [labeled, unlabeled, opened, edited, synchronize]

concurrency:
  group: labelslint-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  enforce:
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@a3c219da6b8fa73f6ba62b68ff09c469b3a1c024 # v2.2.2
        with:
          REQUIRED_LABELS_ANY: "feature,bug,test,enhancement,documentation,chore,autorelease: pending,autorelease: tagged,dependencies,template-sync"
          BANNED_LABELS: "needs-docs,needs-tests,needs-adr,needs-git-sign-off,needs-tutorial"
