name: UDS Lint

on:
  push:
    branches:
      - "main"
    paths:
      - "bundles"
  pull_request:
    branches:
      - "main"
    paths:
      - "bundles"

concurrency:
  group: uds-lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  uds-lint:
    runs-on: ubuntu-latest
    name: Lint UDS Manifest

    permissions:
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: 3.11.6

      - name: Download UDS Schema
        # TODO: renovate setup
        run: curl -o uds.schema.json https://raw.githubusercontent.com/defenseunicorns/uds-cli/v0.10.4/uds.schema.json

      - name: Install jsonschema
        run: pip install check-jsonschema==0.28.0

      - name: Validate uds-bundle.yaml
        run: |
            check-jsonschema bundles/rke2-standard/uds-bundle.yaml --schemafile uds.schema.json
            # TODO: add back in when rke2-slim package is created
            # check-jsonschema bundles/rke2-slim/uds-bundle.yaml --schemafile uds.schema.json

